trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # You can also use 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'mvn test'
    options: '-Dsurefire.suiteXmlFiles=regression-tests.xml' # Optional, if using test suites
